package com.github.nosepass.motoparking.http;

import android.content.SharedPreferences;

import com.github.nosepass.motoparking.MotoParkingApplication;
import com.github.nosepass.motoparking.MyLog;
import com.github.nosepass.motoparking.db.DaoSession;
import com.github.nosepass.motoparking.db.ParkingSpot;

import org.apache.http.client.methods.HttpUriRequest;

/**
 * Add a parking spot to the db.
 */
public class AddSpot extends JSONObjectAction {
    private static final String TAG = "http.AddSpot";
    SharedPreferences prefs;
    ParkingSpot spot;
    ParkingSpot result2;

    public AddSpot(SharedPreferences prefs, ParkingSpot spot) {
        super(prefs);
        this.prefs = prefs;
        this.spot = spot;
    }

    public void executeHttpRequest() {
        // hacktastic
        try {
            MyLog.v(TAG, "downloading stuff");
            ParkingSpotApi api = MotoParkingApplication.parkingSpotApi;
            if (api != null) {
                result2 = api.create(spot);
                statusCode = 200;
            } else {
                throw new Exception("no retrofit api found!");
            }
        } catch (Exception e) {
            MyLog.e(TAG, e);
            errors = true;
            //exception = e;
        }
    }

    @Override
    public void onSuccess() {
        if (result2 != null) {
            // Save new id generated by server, for OCD purposes
            DaoSession s = ParkingDbDownload.daoMaster.newSession();
            spot.setId(result2.getId());
            s.getParkingSpotDao().update(spot);
        } else {
            MyLog.e(TAG, "null result!");
        }
    }

    @Override
    protected HttpUriRequest createRequest() {
        String url = baseUrl +  "/login.json";
        return createPostWithFormParams(url);
    }
}
