package com.github.nosepass.motoparking.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.github.nosepass.motoparking.db.ParkingSpot;

import com.github.nosepass.motoparking.db.ParkingSpotDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig parkingSpotDaoConfig;

    private final ParkingSpotDao parkingSpotDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        parkingSpotDaoConfig = daoConfigMap.get(ParkingSpotDao.class).clone();
        parkingSpotDaoConfig.initIdentityScope(type);

        parkingSpotDao = new ParkingSpotDao(parkingSpotDaoConfig, this);

        registerDao(ParkingSpot.class, parkingSpotDao);
    }
    
    public void clear() {
        parkingSpotDaoConfig.getIdentityScope().clear();
    }

    public ParkingSpotDao getParkingSpotDao() {
        return parkingSpotDao;
    }

}
