package com.github.nosepass.motoparking.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PARKING_SPOT.
 */
public class ParkingSpot {

    private Long id;
    private String name;
    private String description;
    private Boolean paid;
    private Integer spaces;

    public ParkingSpot() {
    }

    public ParkingSpot(Long id) {
        this.id = id;
    }

    public ParkingSpot(Long id, String name, String description, Boolean paid, Integer spaces) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.paid = paid;
        this.spaces = spaces;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getPaid() {
        return paid;
    }

    public void setPaid(Boolean paid) {
        this.paid = paid;
    }

    public Integer getSpaces() {
        return spaces;
    }

    public void setSpaces(Integer spaces) {
        this.spaces = spaces;
    }

}
