package com.github.nosepass.motoparking.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PARKING_SPOT.
 */
public class ParkingSpot {

    private Long localId;
    /** Not-null value. */
    private String id;
    private String name;
    private String description;
    private Double latitude;
    private Double longitude;
    private Boolean paid;
    private Integer spaces;

    public ParkingSpot() {
    }

    public ParkingSpot(Long localId) {
        this.localId = localId;
    }

    public ParkingSpot(Long localId, String id, String name, String description, Double latitude, Double longitude, Boolean paid, Integer spaces) {
        this.localId = localId;
        this.id = id;
        this.name = name;
        this.description = description;
        this.latitude = latitude;
        this.longitude = longitude;
        this.paid = paid;
        this.spaces = spaces;
    }

    public Long getLocalId() {
        return localId;
    }

    public void setLocalId(Long localId) {
        this.localId = localId;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Boolean getPaid() {
        return paid;
    }

    public void setPaid(Boolean paid) {
        this.paid = paid;
    }

    public Integer getSpaces() {
        return spaces;
    }

    public void setSpaces(Integer spaces) {
        this.spaces = spaces;
    }

}
